name: "Test"

on: [push, pull_request]

jobs:
  nose:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packages
      run: ./scripts/tests_setup

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - name: Nosetests
      run: nosetests --logging-level=ERROR

  behave:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packages
      run: ./scripts/tests_setup

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - name: Behave
      run: behave --tags=-sams --format progress2 --logging-level=ERROR

  behave-sams:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: ./scripts/tests_setup

      - name: Start SAMS
        run: ./scripts/install-start-sams

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r dev-requirements.txt

      - name: Behave
        run: behave --tags=sams --format progress2 --logging-level=ERROR

  prodapi:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packages
      run: ./scripts/tests_setup

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - name: prodapi-pytest
      run: cd prod_api && time pytest
