name: "Test"

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mongo:
        image: mongo:3.4
        ports:
          - 27017:27017
      elastic:
        image: elasticsearch:2.4
        ports:
          - 9200:9200

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.5

    - run: |
        python -m pip install wheel setuptools
        pip install -r dev-requirements.txt

    - run: nosetests --logging-level=ERROR
    - run: behave --format progress2 --logging-level ERROR